name: ðŸš€ Deploy Website to dev

on:
  push:
    branches:
      - main

jobs:
  web-deploy:
    name: ðŸŽ‰ Deploy to dev Server
    runs-on: ubuntu-latest

    steps:
      - name: ðŸšš Checkout Latest Code
        uses: actions/checkout@v3

      - name: ðŸ“‚ Sync Files via Rsync
        run: |
          sshpass -p "${{ secrets.PASSWORDDEV }}" rsync -avz -e "ssh -o StrictHostKeyChecking=no" ./ pageart@${{ secrets.HOSTDEV }}:/home/klient.dhosting.pl/pageart/szablonwp.pageart.dev-ook7/public_html/wp-content/